import type { RiskLevel, RuleCondition } from './ruleEngine'

export type AdvancedCandidateRuleConfig = {
  code: string
  name: string
  taxType: string
  level: RiskLevel
  basis: string
  caseRef: string
  conditionJson: RuleCondition
  requiredFields?: string[]
  reason: string
  suggestion: string
  materials: string[]
}

export const advancedCandidateRuleConfigs: AdvancedCandidateRuleConfig[] = [

  {
    code: 'ON-056',
    name: '销项税额显著高于进项税额',
    taxType: '增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：销项税额显著高于进项税额。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'inputTax', operator: '>', value: 0 }, { field: 'outputTax', operator: '>', value: 0, compareField: 'inputTax', multiplier: 3 }] },
    requiredFields: ['inputTax'],
    reason: '基于现有字段的自动检测规则：销项税额显著高于进项税额。',
    suggestion: '复核销项税额显著高于进项税额对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-057',
    name: '有应税销售额但销项税额为零',
    taxType: '增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：有应税销售额但销项税额为零。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'taxableSales', operator: '>', value: 0 }, { field: 'outputTax', operator: '<=', value: 0 }] },
    requiredFields: ['taxableSales'],
    reason: '基于现有字段的自动检测规则：有应税销售额但销项税额为零。',
    suggestion: '复核有应税销售额但销项税额为零对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-058',
    name: '应纳增值税额高于销项税额',
    taxType: '增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：应纳增值税额高于销项税额。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'outputTax', operator: '>', value: 0 }, { field: 'vatTaxPayable', operator: '>', value: 0, compareField: 'outputTax', multiplier: 1.05 }] },
    requiredFields: ['outputTax'],
    reason: '基于现有字段的自动检测规则：应纳增值税额高于销项税额。',
    suggestion: '复核应纳增值税额高于销项税额对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-059',
    name: '实际增值税低于理论税额五成',
    taxType: '增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：实际增值税低于理论税额五成。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'theoreticalVatTax', operator: '>', value: 0 }, { field: 'vatTaxPayable', operator: '<', value: 0, compareField: 'theoreticalVatTax', multiplier: 0.5 }] },
    requiredFields: ['theoreticalVatTax'],
    reason: '基于现有字段的自动检测规则：实际增值税低于理论税额五成。',
    suggestion: '复核实际增值税低于理论税额五成对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-060',
    name: '实际增值税高于理论税额五成',
    taxType: '增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：实际增值税高于理论税额五成。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'theoreticalVatTax', operator: '>', value: 0 }, { field: 'vatTaxPayable', operator: '>', value: 0, compareField: 'theoreticalVatTax', multiplier: 1.5 }] },
    requiredFields: ['theoreticalVatTax'],
    reason: '基于现有字段的自动检测规则：实际增值税高于理论税额五成。',
    suggestion: '复核实际增值税高于理论税额五成对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-061',
    name: '增值税税额显著低于预算',
    taxType: '增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：增值税税额显著低于预算。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'budgetVatTax', operator: '>', value: 0 }, { field: 'vatTaxPayable', operator: '<', value: 0, compareField: 'budgetVatTax', multiplier: 0.5 }] },
    requiredFields: ['budgetVatTax'],
    reason: '基于现有字段的自动检测规则：增值税税额显著低于预算。',
    suggestion: '复核增值税税额显著低于预算对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-062',
    name: '增值税税额显著高于预算',
    taxType: '增值税',
    level: '低',
    basis: '基于现有字段的自动检测规则：增值税税额显著高于预算。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'budgetVatTax', operator: '>', value: 0 }, { field: 'vatTaxPayable', operator: '>', value: 0, compareField: 'budgetVatTax', multiplier: 1.5 }] },
    requiredFields: ['budgetVatTax'],
    reason: '基于现有字段的自动检测规则：增值税税额显著高于预算。',
    suggestion: '复核增值税税额显著高于预算对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-063',
    name: '期末留抵税额高于销项税额',
    taxType: '增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：期末留抵税额高于销项税额。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'outputTax', operator: '>', value: 0 }, { field: 'endingVatCredit', operator: '>', value: 0, compareField: 'outputTax', multiplier: 1 }] },
    requiredFields: ['outputTax'],
    reason: '基于现有字段的自动检测规则：期末留抵税额高于销项税额。',
    suggestion: '复核期末留抵税额高于销项税额对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-064',
    name: '红字专票金额高于销项税额',
    taxType: '增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：红字专票金额高于销项税额。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'outputTax', operator: '>', value: 0 }, { field: 'redVatSpecialInvoiceAmount', operator: '>', value: 0, compareField: 'outputTax', multiplier: 1 }] },
    requiredFields: ['outputTax'],
    reason: '基于现有字段的自动检测规则：红字专票金额高于销项税额。',
    suggestion: '复核红字专票金额高于销项税额对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-065',
    name: '开票金额高于收款流水',
    taxType: '增值税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：开票金额高于收款流水。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'collectionFlow', operator: '>', value: 0 }, { field: 'monthlyInvoice', operator: '>', value: 0, compareField: 'collectionFlow', multiplier: 1.2 }] },
    requiredFields: ['collectionFlow'],
    reason: '基于现有字段的自动检测规则：开票金额高于收款流水。',
    suggestion: '复核开票金额高于收款流水对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-066',
    name: '平台收入显著高于申报收入',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：平台收入显著高于申报收入。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'monthlyRevenue', operator: '>', value: 0 }, { field: 'platformRevenue', operator: '>', value: 0, compareField: 'monthlyRevenue', multiplier: 1.2 }] },
    requiredFields: ['monthlyRevenue'],
    reason: '基于现有字段的自动检测规则：平台收入显著高于申报收入。',
    suggestion: '复核平台收入显著高于申报收入对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-067',
    name: '收款流水低于申报收入较多',
    taxType: '企业所得税、增值税',
    level: '低',
    basis: '基于现有字段的自动检测规则：收款流水低于申报收入较多。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'monthlyRevenue', operator: '>', value: 0 }, { field: 'collectionFlow', operator: '<', value: 0, compareField: 'monthlyRevenue', multiplier: 0.6 }] },
    requiredFields: ['monthlyRevenue'],
    reason: '基于现有字段的自动检测规则：收款流水低于申报收入较多。',
    suggestion: '复核收款流水低于申报收入较多对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-068',
    name: '月利润率偏高',
    taxType: '企业所得税',
    level: '低',
    basis: '基于现有字段的自动检测规则：月利润率偏高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'monthlyRevenue', operator: '>', value: 0 }, { field: 'monthlyProfit', operator: '>', value: 0, compareField: 'monthlyRevenue', multiplier: 0.5 }] },
    requiredFields: ['monthlyRevenue'],
    reason: '基于现有字段的自动检测规则：月利润率偏高。',
    suggestion: '复核月利润率偏高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-069',
    name: '月利润率偏低',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：月利润率偏低。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'monthlyRevenue', operator: '>', value: 0 }, { field: 'monthlyProfit', operator: '<', value: 0, compareField: 'monthlyRevenue', multiplier: 0.02 }] },
    requiredFields: ['monthlyRevenue'],
    reason: '基于现有字段的自动检测规则：月利润率偏低。',
    suggestion: '复核月利润率偏低对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-070',
    name: '月成本高于月收入',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：月成本高于月收入。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'monthlyRevenue', operator: '>', value: 0 }, { field: 'monthlyCost', operator: '>', value: 0, compareField: 'monthlyRevenue', multiplier: 1 }] },
    requiredFields: ['monthlyRevenue'],
    reason: '基于现有字段的自动检测规则：月成本高于月收入。',
    suggestion: '复核月成本高于月收入对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-071',
    name: '年销售收入高但员工人数过少',
    taxType: '增值税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：年销售收入高但员工人数过少。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 50000000 }, { field: 'employees', operator: '<', value: 3 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：年销售收入高但员工人数过少。',
    suggestion: '复核年销售收入高但员工人数过少对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-072',
    name: '连续12个月销售额与年收入差异过大',
    taxType: '增值税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：连续12个月销售额与年收入差异过大。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 0 }, { field: 'consecutive12MonthSales', operator: '>', value: 0, compareField: 'annualRevenue', multiplier: 1.3 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：连续12个月销售额与年收入差异过大。',
    suggestion: '复核连续12个月销售额与年收入差异过大对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-073',
    name: '年收入高于连续12个月销售额较多',
    taxType: '增值税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：年收入高于连续12个月销售额较多。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'consecutive12MonthSales', operator: '>', value: 0 }, { field: 'annualRevenue', operator: '>', value: 0, compareField: 'consecutive12MonthSales', multiplier: 1.3 }] },
    requiredFields: ['consecutive12MonthSales'],
    reason: '基于现有字段的自动检测规则：年收入高于连续12个月销售额较多。',
    suggestion: '复核年收入高于连续12个月销售额较多对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-074',
    name: '享受小微优惠但收入规模较大',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：享受小微优惠但收入规模较大。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'smallProfitEnjoyed', operator: '=', value: true }, { field: 'annualRevenue', operator: '>', value: 30000000 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：享受小微优惠但收入规模较大。',
    suggestion: '复核享受小微优惠但收入规模较大对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-075',
    name: '享受研发加计但研发资料不足',
    taxType: '企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：享受研发加计但研发资料不足。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'rdDeductionEnjoyed', operator: '=', value: true }, { field: 'rdDocsInsufficient', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：享受研发加计但研发资料不足。',
    suggestion: '复核享受研发加计但研发资料不足对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-076',
    name: '享受税费优惠但资料不足',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：享受税费优惠但资料不足。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { field: 'taxBenefitDataMissing', operator: '=', value: true },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：享受税费优惠但资料不足。',
    suggestion: '复核享受税费优惠但资料不足对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-077',
    name: '长期亏损且仍有较大收入',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：长期亏损且仍有较大收入。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'longTermLoss', operator: '=', value: true }, { field: 'annualRevenue', operator: '>', value: 10000000 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：长期亏损且仍有较大收入。',
    suggestion: '复核长期亏损且仍有较大收入对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-078',
    name: '长期零申报但有开票金额',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：长期零申报但有开票金额。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'longTermZeroDeclaration', operator: '=', value: true }, { field: 'monthlyInvoice', operator: '>', value: 0 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：长期零申报但有开票金额。',
    suggestion: '复核长期零申报但有开票金额对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-079',
    name: '长期零申报但有收款流水',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：长期零申报但有收款流水。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'longTermZeroDeclaration', operator: '=', value: true }, { field: 'collectionFlow', operator: '>', value: 0 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：长期零申报但有收款流水。',
    suggestion: '复核长期零申报但有收款流水对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-080',
    name: '长期零申报但有成本费用',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：长期零申报但有成本费用。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'longTermZeroDeclaration', operator: '=', value: true }, { field: 'ytdCostExpense', operator: '>', value: 0 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：长期零申报但有成本费用。',
    suggestion: '复核长期零申报但有成本费用对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-081',
    name: '大额费用无票且费用规模较高',
    taxType: '企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：大额费用无票且费用规模较高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'largeExpenseNoInvoice', operator: '=', value: true }, { field: 'ytdCostExpense', operator: '>', value: 1000000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：大额费用无票且费用规模较高。',
    suggestion: '复核大额费用无票且费用规模较高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-082',
    name: '服务费发票异常且金额结构偏高',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：服务费发票异常且金额结构偏高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'serviceFeeInvoices', operator: '=', value: true }, { field: 'ytdCostExpense', operator: '>', value: 1000000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：服务费发票异常且金额结构偏高。',
    suggestion: '复核服务费发票异常且金额结构偏高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-083',
    name: '供应商无进项且存在较大进项税额',
    taxType: '增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：供应商无进项且存在较大进项税额。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'supplierNoInput', operator: '=', value: true }, { field: 'inputTax', operator: '>', value: 100000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：供应商无进项且存在较大进项税额。',
    suggestion: '复核供应商无进项且存在较大进项税额对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-084',
    name: '发票品名不匹配且采购销售不匹配',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：发票品名不匹配且采购销售不匹配。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'invoiceNameMismatch', operator: '=', value: true }, { field: 'purchaseSalesMismatch', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：发票品名不匹配且采购销售不匹配。',
    suggestion: '复核发票品名不匹配且采购销售不匹配对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-085',
    name: '资金回流且异常发票入账',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：资金回流且异常发票入账。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'fundsReturn', operator: '=', value: true }, { field: 'abnormalInvoice', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：资金回流且异常发票入账。',
    suggestion: '复核资金回流且异常发票入账对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-086',
    name: '关联定价异常且长期亏损',
    taxType: '企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：关联定价异常且长期亏损。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'relatedPricingAbnormal', operator: '=', value: true }, { field: 'longTermLoss', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：关联定价异常且长期亏损。',
    suggestion: '复核关联定价异常且长期亏损对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-087',
    name: '关联交易且管理费异常',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：关联交易且管理费异常。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'relatedTransactions', operator: '=', value: true }, { field: 'intercompanyManagementFee', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：关联交易且管理费异常。',
    suggestion: '复核关联交易且管理费异常对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-088',
    name: '非金融利息异常且资产规模较高',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：非金融利息异常且资产规模较高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'nonFinancialInterestAbnormal', operator: '=', value: true }, { field: 'assetsTotal', operator: '>', value: 10000000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：非金融利息异常且资产规模较高。',
    suggestion: '复核非金融利息异常且资产规模较高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-089',
    name: '工资拆分且个人非工资支付较大',
    taxType: '个人所得税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：工资拆分且个人非工资支付较大。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'salarySplit', operator: '=', value: true }, { field: 'nonPayrollPersonalPayment', operator: '>', value: 100000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：工资拆分且个人非工资支付较大。',
    suggestion: '复核工资拆分且个人非工资支付较大对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-090',
    name: '未履行个税扣缴且个人支付较大',
    taxType: '个人所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：未履行个税扣缴且个人支付较大。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'noIitWithholding', operator: '=', value: true }, { field: 'nonPayrollPersonalPayment', operator: '>', value: 50000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：未履行个税扣缴且个人支付较大。',
    suggestion: '复核未履行个税扣缴且个人支付较大对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-091',
    name: '工资人数与社保人数差异超过50%',
    taxType: '个人所得税、社保费',
    level: '高',
    basis: '基于现有字段的自动检测规则：工资人数与社保人数差异超过50%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'socialSecurityCount', operator: '>', value: 0 }, { field: 'salaryDeclaredCount', operator: '>', value: 0, compareField: 'socialSecurityCount', multiplier: 1.5 }] },
    requiredFields: ['socialSecurityCount'],
    reason: '基于现有字段的自动检测规则：工资人数与社保人数差异超过50%。',
    suggestion: '复核工资人数与社保人数差异超过50%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-092',
    name: '社保人数高于工资人数较多',
    taxType: '个人所得税、社保费',
    level: '中',
    basis: '基于现有字段的自动检测规则：社保人数高于工资人数较多。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'salaryDeclaredCount', operator: '>', value: 0 }, { field: 'socialSecurityCount', operator: '>', value: 0, compareField: 'salaryDeclaredCount', multiplier: 1.5 }] },
    requiredFields: ['salaryDeclaredCount'],
    reason: '基于现有字段的自动检测规则：社保人数高于工资人数较多。',
    suggestion: '复核社保人数高于工资人数较多对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-093',
    name: '劳务人数超过员工人数',
    taxType: '个人所得税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：劳务人数超过员工人数。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'employees', operator: '>', value: 0 }, { field: 'laborCount', operator: '>', value: 0, compareField: 'employees', multiplier: 1 }] },
    requiredFields: ['employees'],
    reason: '基于现有字段的自动检测规则：劳务人数超过员工人数。',
    suggestion: '复核劳务人数超过员工人数对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-094',
    name: '人均福利费偏高',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：人均福利费偏高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'employees', operator: '>', value: 0 }, { field: 'welfareExpense', operator: '>', value: 0, compareField: 'employees', multiplier: 30000 }] },
    requiredFields: ['employees'],
    reason: '基于现有字段的自动检测规则：人均福利费偏高。',
    suggestion: '复核人均福利费偏高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-095',
    name: '人均业务招待费偏高',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：人均业务招待费偏高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'employees', operator: '>', value: 0 }, { field: 'entertainmentExpense', operator: '>', value: 0, compareField: 'employees', multiplier: 30000 }] },
    requiredFields: ['employees'],
    reason: '基于现有字段的自动检测规则：人均业务招待费偏高。',
    suggestion: '复核人均业务招待费偏高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-096',
    name: '广告宣传费占收入超过30%',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：广告宣传费占收入超过30%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 0 }, { field: 'adExpense', operator: '>', value: 0, compareField: 'annualRevenue', multiplier: 0.3 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：广告宣传费占收入超过30%。',
    suggestion: '复核广告宣传费占收入超过30%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-097',
    name: '业务招待费占收入超过1%',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：业务招待费占收入超过1%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 0 }, { field: 'entertainmentExpense', operator: '>', value: 0, compareField: 'annualRevenue', multiplier: 0.01 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：业务招待费占收入超过1%。',
    suggestion: '复核业务招待费占收入超过1%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-098',
    name: '职工教育经费占工资超过12%',
    taxType: '企业所得税',
    level: '低',
    basis: '基于现有字段的自动检测规则：职工教育经费占工资超过12%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'payrollTotal', operator: '>', value: 0 }, { field: 'educationExpense', operator: '>', value: 0, compareField: 'payrollTotal', multiplier: 0.12 }] },
    requiredFields: ['payrollTotal'],
    reason: '基于现有字段的自动检测规则：职工教育经费占工资超过12%。',
    suggestion: '复核职工教育经费占工资超过12%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-099',
    name: '工会经费占工资超过3%',
    taxType: '企业所得税',
    level: '低',
    basis: '基于现有字段的自动检测规则：工会经费占工资超过3%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'payrollTotal', operator: '>', value: 0 }, { field: 'unionExpense', operator: '>', value: 0, compareField: 'payrollTotal', multiplier: 0.03 }] },
    requiredFields: ['payrollTotal'],
    reason: '基于现有字段的自动检测规则：工会经费占工资超过3%。',
    suggestion: '复核工会经费占工资超过3%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-100',
    name: '装修费用超过年收入10%',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：装修费用超过年收入10%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 0 }, { field: 'decorationExpense', operator: '>', value: 0, compareField: 'annualRevenue', multiplier: 0.1 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：装修费用超过年收入10%。',
    suggestion: '复核装修费用超过年收入10%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-101',
    name: '装修费用高但无租赁面积',
    taxType: '企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：装修费用高但无租赁面积。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'rentalArea', operator: '<=', value: 0 }, { field: 'decorationExpense', operator: '>', value: 0 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：装修费用高但无租赁面积。',
    suggestion: '复核装修费用高但无租赁面积对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-102',
    name: '人员相关费用高但员工人数少',
    taxType: '企业所得税、个人所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：人员相关费用高但员工人数少。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'employees', operator: '<', value: 3 }, { field: 'peopleRelatedExpense', operator: '>', value: 200000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：人员相关费用高但员工人数少。',
    suggestion: '复核人员相关费用高但员工人数少对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-103',
    name: '代收代付余额超过收入10%',
    taxType: '企业所得税、增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：代收代付余额超过收入10%。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 0 }, { field: 'otherReceivableAgencyBalance', operator: '>', value: 0, compareField: 'annualRevenue', multiplier: 0.1 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：代收代付余额超过收入10%。',
    suggestion: '复核代收代付余额超过收入10%对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-104',
    name: '营业外收入占收入比例偏高',
    taxType: '企业所得税',
    level: '低',
    basis: '基于现有字段的自动检测规则：营业外收入占收入比例偏高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'annualRevenue', operator: '>', value: 0 }, { field: 'nonOperatingIncome', operator: '>', value: 0, compareField: 'annualRevenue', multiplier: 0.05 }] },
    requiredFields: ['annualRevenue'],
    reason: '基于现有字段的自动检测规则：营业外收入占收入比例偏高。',
    suggestion: '复核营业外收入占收入比例偏高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-105',
    name: '营业外收支同时较大',
    taxType: '企业所得税',
    level: '低',
    basis: '基于现有字段的自动检测规则：营业外收支同时较大。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'nonOperatingIncome', operator: '>', value: 100000 }, { field: 'nonOperatingExpense', operator: '>', value: 100000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：营业外收支同时较大。',
    suggestion: '复核营业外收支同时较大对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-106',
    name: '资产总额接近小微上限',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：资产总额接近小微上限。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'smallProfitEnjoyed', operator: '=', value: true }, { field: 'assetsTotal', operator: '>', value: 45000000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：资产总额接近小微上限。',
    suggestion: '复核资产总额接近小微上限对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-107',
    name: '人数接近小微上限',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：人数接近小微上限。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'smallProfitEnjoyed', operator: '=', value: true }, { field: 'employeeAnnualAvg', operator: '>', value: 260 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：人数接近小微上限。',
    suggestion: '复核人数接近小微上限对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-108',
    name: '应纳税所得额接近小微上限',
    taxType: '企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：应纳税所得额接近小微上限。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'smallProfitEnjoyed', operator: '=', value: true }, { field: 'taxableIncome', operator: '>', value: 2500000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：应纳税所得额接近小微上限。',
    suggestion: '复核应纳税所得额接近小微上限对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },
  {
    code: 'ON-109',
    name: '平台收入存在但无员工',
    taxType: '增值税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：平台收入存在但无员工。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'platformRevenue', operator: '>', value: 0 }, { field: 'employees', operator: '<=', value: 0 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：平台收入存在但无员工。',
    suggestion: '复核平台收入存在但无员工对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-110',
    name: '平台收入存在但无收款流水',
    taxType: '增值税、企业所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：平台收入存在但无收款流水。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'platformRevenue', operator: '>', value: 0 }, { field: 'collectionFlow', operator: '<=', value: 0 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：平台收入存在但无收款流水。',
    suggestion: '复核平台收入存在但无收款流水对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-111',
    name: '私户收款且收款流水较大',
    taxType: '增值税、企业所得税、个人所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：私户收款且收款流水较大。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'privateAccountCollection', operator: '=', value: true }, { field: 'collectionFlow', operator: '>', value: 500000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：私户收款且收款流水较大。',
    suggestion: '复核私户收款且收款流水较大对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-112',
    name: '未开票收入标记且开票低于收入',
    taxType: '增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：未开票收入标记且开票低于收入。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'unbilledIncome', operator: '=', value: true }, { field: 'monthlyRevenue', operator: '>', value: 0, compareField: 'monthlyInvoice', multiplier: 1.2 }] },
    requiredFields: ['monthlyInvoice'],
    reason: '基于现有字段的自动检测规则：未开票收入标记且开票低于收入。',
    suggestion: '复核未开票收入标记且开票低于收入对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-113',
    name: '接近免税临界且存在未开票收入',
    taxType: '增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：接近免税临界且存在未开票收入。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'nearVatExemption', operator: '=', value: true }, { field: 'unbilledIncome', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：接近免税临界且存在未开票收入。',
    suggestion: '复核接近免税临界且存在未开票收入对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-114',
    name: '接近一般纳税人标准且有关联主体',
    taxType: '增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：接近一般纳税人标准且有关联主体。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'relatedEntitiesNearThreshold', operator: '=', value: true }, { field: 'consecutive12MonthSales', operator: '>', value: 4000000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：接近一般纳税人标准且有关联主体。',
    suggestion: '复核接近一般纳税人标准且有关联主体对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-115',
    name: '个体户关联供应商且服务费异常',
    taxType: '个人所得税、企业所得税、增值税',
    level: '高',
    basis: '基于现有字段的自动检测规则：个体户关联供应商且服务费异常。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'individualVendorRelated', operator: '=', value: true }, { field: 'serviceFeeInvoices', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：个体户关联供应商且服务费异常。',
    suggestion: '复核个体户关联供应商且服务费异常对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-116',
    name: '库存异常且进销不匹配',
    taxType: '增值税、企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：库存异常且进销不匹配。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'inventoryAbnormal', operator: '=', value: true }, { field: 'purchaseSalesMismatch', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：库存异常且进销不匹配。',
    suggestion: '复核库存异常且进销不匹配对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-117',
    name: '库存异常且成本高于收入',
    taxType: '企业所得税、增值税',
    level: '中',
    basis: '基于现有字段的自动检测规则：库存异常且成本高于收入。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'inventoryAbnormal', operator: '=', value: true }, { field: 'mainBusinessCost', operator: '>', value: 0, compareField: 'mainBusinessRevenue', multiplier: 1 }] },
    requiredFields: ['mainBusinessRevenue'],
    reason: '基于现有字段的自动检测规则：库存异常且成本高于收入。',
    suggestion: '复核库存异常且成本高于收入对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['增值税申报表', '销项/进项发票明细', '收入或收款明细', '差异说明'],
  },
  {
    code: 'ON-118',
    name: '涉税服务合规风险且资料不足',
    taxType: '通用财务/经营',
    level: '中',
    basis: '基于现有字段的自动检测规则：涉税服务合规风险且资料不足。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'agencyComplianceRisk', operator: '=', value: true }, { field: 'taxBenefitDataMissing', operator: '=', value: true }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：涉税服务合规风险且资料不足。',
    suggestion: '复核涉税服务合规风险且资料不足对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['规则命中数据', '申报表或账务明细', '合同/发票/付款凭证', '差异说明'],
  },
  {
    code: 'ON-119',
    name: '研发加计且工资社保人数差异',
    taxType: '企业所得税、个人所得税',
    level: '中',
    basis: '基于现有字段的自动检测规则：研发加计且工资社保人数差异。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'rdDeductionEnjoyed', operator: '=', value: true }, { field: 'salaryDeclaredCount', operator: '>=', value: 3, compareField: 'socialSecurityCount', transform: 'absDiff' }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：研发加计且工资社保人数差异。',
    suggestion: '复核研发加计且工资社保人数差异对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['工资表', '社保清单', '个税扣缴申报表', '用工或支付说明'],
  },
  {
    code: 'ON-120',
    name: '优惠资料不足且应纳税所得额较高',
    taxType: '企业所得税',
    level: '高',
    basis: '基于现有字段的自动检测规则：优惠资料不足且应纳税所得额较高。',
    caseRef: '第三批可执行候选：基于现有字段的自动检测规则。',
    conditionJson: { all: [{ field: 'taxBenefitDataMissing', operator: '=', value: true }, { field: 'taxableIncome', operator: '>', value: 1000000 }] },
    requiredFields: [],
    reason: '基于现有字段的自动检测规则：优惠资料不足且应纳税所得额较高。',
    suggestion: '复核优惠资料不足且应纳税所得额较高对应的数据来源、申报口径、业务凭证和差异原因。',
    materials: ['企业所得税申报表', '财务报表', '成本费用明细', '纳税调整底稿'],
  },

]
