export const taxDataIntakeMigration = {
  id: '0008_full_tax_data_intake',
  tables: [
    'tax_data_import_batches',
    'tax_data_source_files',
    'tax_data_periods',
    'tax_data_financial_statements',
    'tax_data_financial_statement_lines',
    'tax_data_account_balances',
    'tax_data_ledger_entries',
    'tax_data_vat_returns',
    'tax_data_vat_return_lines',
    'tax_data_invoice_summaries',
    'tax_data_invoice_lines',
    'tax_data_payroll_runs',
    'tax_data_payroll_lines',
    'tax_data_iit_returns',
    'tax_data_iit_return_lines',
    'tax_data_evidence_fields',
    'tax_data_conflicts',
    'tax_data_standard_records',
  ],
  statements: [
    `CREATE TABLE IF NOT EXISTS tax_data_import_batches (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      thread_id TEXT,
      client_id TEXT,
      client_name TEXT,
      client_credit_code TEXT,
      period_start TEXT,
      period_end TEXT,
      source_system TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      summary_json TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_import_batches_owner_updated
      ON tax_data_import_batches(owner_user_id, updated_at)`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_import_batches_client
      ON tax_data_import_batches(client_id, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_source_files (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      batch_id TEXT NOT NULL,
      material_id TEXT,
      client_id TEXT,
      file_name TEXT NOT NULL,
      file_hash TEXT,
      content_type TEXT,
      file_size INTEGER,
      document_type TEXT NOT NULL,
      source_system TEXT,
      period_start TEXT,
      period_end TEXT,
      parse_status TEXT NOT NULL DEFAULT 'pending',
      storage_key TEXT,
      evidence_json TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (batch_id) REFERENCES tax_data_import_batches(id) ON DELETE CASCADE
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_source_files_batch
      ON tax_data_source_files(batch_id)`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_source_files_client_period
      ON tax_data_source_files(client_id, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_periods (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      period_type TEXT NOT NULL,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      data_basis TEXT,
      source_file_ids TEXT NOT NULL DEFAULT '[]',
      validation_json TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_tax_data_periods_unique
      ON tax_data_periods(owner_user_id, client_id, period_type, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_financial_statements (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      statement_type TEXT NOT NULL,
      accounting_standard TEXT,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      currency TEXT NOT NULL DEFAULT 'CNY',
      totals_json TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_financial_statements_client_period
      ON tax_data_financial_statements(client_id, statement_type, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_financial_statement_lines (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      statement_id TEXT NOT NULL,
      line_code TEXT,
      line_name TEXT NOT NULL,
      row_no INTEGER,
      current_amount REAL,
      cumulative_amount REAL,
      beginning_amount REAL,
      ending_amount REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}',
      FOREIGN KEY (statement_id) REFERENCES tax_data_financial_statements(id) ON DELETE CASCADE
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_financial_statement_lines_statement
      ON tax_data_financial_statement_lines(statement_id)`,
    `CREATE TABLE IF NOT EXISTS tax_data_account_balances (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      account_code TEXT NOT NULL,
      account_name TEXT NOT NULL,
      opening_debit REAL,
      opening_credit REAL,
      current_debit REAL,
      current_credit REAL,
      ytd_debit REAL,
      ytd_credit REAL,
      ending_debit REAL,
      ending_credit REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}'
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_account_balances_client_period
      ON tax_data_account_balances(client_id, period_start, period_end, account_code)`,
    `CREATE TABLE IF NOT EXISTS tax_data_ledger_entries (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      entry_date TEXT,
      voucher_no TEXT,
      account_code TEXT,
      account_name TEXT,
      summary TEXT,
      debit_amount REAL,
      credit_amount REAL,
      direction TEXT,
      balance_amount REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}'
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_ledger_entries_client_date
      ON tax_data_ledger_entries(client_id, entry_date, account_code)`,
    `CREATE TABLE IF NOT EXISTS tax_data_vat_returns (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      return_type TEXT NOT NULL,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      taxpayer_type TEXT,
      sales_amount REAL,
      output_tax REAL,
      input_tax REAL,
      tax_payable REAL,
      tax_paid REAL,
      retained_tax_credit REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_vat_returns_client_period
      ON tax_data_vat_returns(client_id, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_vat_return_lines (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      vat_return_id TEXT NOT NULL,
      form_name TEXT NOT NULL,
      row_no TEXT,
      item_name TEXT NOT NULL,
      current_amount REAL,
      cumulative_amount REAL,
      current_tax REAL,
      cumulative_tax REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}',
      FOREIGN KEY (vat_return_id) REFERENCES tax_data_vat_returns(id) ON DELETE CASCADE
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_vat_return_lines_return
      ON tax_data_vat_return_lines(vat_return_id)`,
    `CREATE TABLE IF NOT EXISTS tax_data_invoice_summaries (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      invoice_direction TEXT NOT NULL,
      invoice_count INTEGER,
      amount_total REAL,
      tax_total REAL,
      valid_deduction_tax REAL,
      raw_json TEXT NOT NULL DEFAULT '{}'
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_invoice_summaries_client_period
      ON tax_data_invoice_summaries(client_id, period_start, period_end, invoice_direction)`,
    `CREATE TABLE IF NOT EXISTS tax_data_invoice_lines (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      invoice_direction TEXT NOT NULL,
      invoice_no TEXT,
      invoice_code TEXT,
      invoice_date TEXT,
      counterparty_credit_code TEXT,
      counterparty_name TEXT,
      goods_name TEXT,
      amount REAL,
      tax_amount REAL,
      effective_deduction_tax REAL,
      invoice_status TEXT,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}'
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_invoice_lines_client_date
      ON tax_data_invoice_lines(client_id, invoice_direction, invoice_date)`,
    `CREATE TABLE IF NOT EXISTS tax_data_payroll_runs (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      employee_count INTEGER,
      gross_pay_total REAL,
      social_security_total REAL,
      housing_fund_total REAL,
      taxable_income_total REAL,
      iit_withheld_total REAL,
      raw_json TEXT NOT NULL DEFAULT '{}'
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_payroll_runs_client_period
      ON tax_data_payroll_runs(client_id, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_payroll_lines (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      payroll_run_id TEXT NOT NULL,
      employee_name TEXT,
      id_type TEXT,
      id_number_masked TEXT,
      gross_pay REAL,
      social_security REAL,
      medical_insurance REAL,
      unemployment_insurance REAL,
      housing_fund REAL,
      taxable_income REAL,
      tax_rate REAL,
      tax_withheld REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}',
      FOREIGN KEY (payroll_run_id) REFERENCES tax_data_payroll_runs(id) ON DELETE CASCADE
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_payroll_lines_run
      ON tax_data_payroll_lines(payroll_run_id)`,
    `CREATE TABLE IF NOT EXISTS tax_data_iit_returns (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      client_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      withholding_agent_name TEXT,
      withholding_agent_credit_code TEXT,
      income_item TEXT,
      employee_count INTEGER,
      income_total REAL,
      taxable_income_total REAL,
      tax_withheld_total REAL,
      raw_json TEXT NOT NULL DEFAULT '{}'
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_iit_returns_client_period
      ON tax_data_iit_returns(client_id, period_start, period_end)`,
    `CREATE TABLE IF NOT EXISTS tax_data_iit_return_lines (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      iit_return_id TEXT NOT NULL,
      person_name TEXT,
      id_type TEXT,
      id_number_masked TEXT,
      income_item TEXT,
      current_income REAL,
      cumulative_income REAL,
      cumulative_deduction REAL,
      taxable_income REAL,
      tax_rate REAL,
      tax_withheld REAL,
      raw_json TEXT NOT NULL DEFAULT '{}',
      evidence_json TEXT NOT NULL DEFAULT '{}',
      FOREIGN KEY (iit_return_id) REFERENCES tax_data_iit_returns(id) ON DELETE CASCADE
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_iit_return_lines_return
      ON tax_data_iit_return_lines(iit_return_id)`,
    `CREATE TABLE IF NOT EXISTS tax_data_evidence_fields (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      batch_id TEXT,
      source_file_id TEXT,
      target_table TEXT NOT NULL,
      target_id TEXT,
      target_field TEXT NOT NULL,
      raw_value TEXT,
      normalized_value TEXT,
      confidence TEXT NOT NULL DEFAULT 'medium',
      sheet_name TEXT,
      row_no INTEGER,
      column_no INTEGER,
      page_no INTEGER,
      note TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_evidence_fields_target
      ON tax_data_evidence_fields(target_table, target_id, target_field)`,
    `CREATE TABLE IF NOT EXISTS tax_data_conflicts (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      batch_id TEXT,
      client_id TEXT,
      conflict_type TEXT NOT NULL,
      field_name TEXT,
      existing_value TEXT,
      incoming_value TEXT,
      source_file_ids TEXT NOT NULL DEFAULT '[]',
      severity TEXT NOT NULL DEFAULT 'medium',
      status TEXT NOT NULL DEFAULT 'open',
      resolution TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_conflicts_client_status
      ON tax_data_conflicts(client_id, status)`,
    `CREATE TABLE IF NOT EXISTS tax_data_standard_records (
      id TEXT PRIMARY KEY,
      owner_user_id TEXT NOT NULL,
      batch_id TEXT NOT NULL,
      client_id TEXT,
      source_file_id TEXT,
      record_type TEXT NOT NULL,
      record_subtype TEXT,
      period_start TEXT,
      period_end TEXT,
      record_json TEXT NOT NULL,
      confidence TEXT NOT NULL DEFAULT 'medium',
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (batch_id) REFERENCES tax_data_import_batches(id) ON DELETE CASCADE
    )`,
    `CREATE INDEX IF NOT EXISTS idx_tax_data_standard_records_batch
      ON tax_data_standard_records(batch_id, record_type)`,
  ],
}

export async function ensureTaxDataIntakeTables(db) {
  for (const statement of taxDataIntakeMigration.statements) {
    await db.prepare(statement).run()
  }
}
